<?php

function workbench_moderation_buttons_form_node_form_alter(&$form, $state, $id){
    global $user;
    
    $currentState = variable_get('workbench_moderation_default_state_' . $form['type']['#value'], workbench_moderation_state_none());
    $stateMachineNames = array_merge(array($currentState), array_keys(workbench_moderation_states_next($currentState, $user, $form['#node'])));
    
    if (count($stateMachineNames)){ // If any state is defined, and this user have access to them.
        $states = workbench_moderation_states();
        $actions = &$form['actions'];
        
        // Hide moderation states dropdown.
        drupal_add_css('.form-item-workbench-moderation-state-new{display:none;}', array('type'=>'inline'));
        
        $labelMachineNames = array();
        for($i=0,$length=count($stateMachineNames); $i<$length; $i++){
            $machineName = $stateMachineNames[$i];
            $label = t($states[$machineName]->description);
            $actions[$machineName] = array(
                '#access' => 1,
                '#attributes' => array(
                    'data-value' => $machineName
                ),
                '#submit' => $actions['submit']['#submit'],
                '#type' => 'submit',
                '#value' => $label,
                '#weight' => 11+$i // 10's the weight for preview button.
            );
            $labelMachineNames[$label] = $machineName;
        };
        
        $form['#validate'][] = 'workbench_moderation_buttons_node_form_validate';
        $form['#workbench_moderation_buttons_list'] = $labelMachineNames;
        unset($actions['submit']); // Remove original submit button.
    }
}

function workbench_moderation_buttons_node_form_validate($form, &$form_state){
    $vals = &$form_state['values'];
    $buttonList = $form['#workbench_moderation_buttons_list'];
    $submitButtonLabel = $vals['op'];
    
    if (isSet($buttonList[$submitButtonLabel])){
        $vals['workbench_moderation_state_new'] = $buttonList[$submitButtonLabel];
    }
}
